# Generated by Django 4.2.7 on 2026-02-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_event_based_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science'), ('ECE', 'Electronics & Communication'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('AIML', 'Artificial Intelligence & Machine Learning'), ('AIDS', 'Artificial Intelligence & Data Science'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
